// Thieves' Cant Dictionary Data
// Based on "Dictionary of the Vulgar Tongue" (1811)

export interface DictionaryEntry {
  term: string;
  definition: string;
  category?: string;
}

export const cantToEnglish: DictionaryEntry[] = [
  { term: "Abbess", definition: "The mistress of a brothel", category: "People" },
  { term: "Abram", definition: "Naked", category: "Descriptive" },
  { term: "Abram cove", definition: "A naked or poor man; also a lusty strong rogue", category: "People" },
  { term: "Abram men", definition: "A beggar who pretends to be mad", category: "People" },
  { term: "Academy", definition: "Brothel", category: "Places" },
  { term: "Ace of spades", definition: "A widow", category: "People" },
  { term: "Acorn", definition: "To ride a horse foaled by an acorn is to be hanged on the gallows", category: "Execution" },
  { term: "Adam Tiler", definition: "A pickpocket's associate who receives stolen goods and runs off with them", category: "People" },
  { term: "Affidavit Men", definition: "A witness for hire who will swear to anything in court", category: "People" },
  { term: "Air and exercise", definition: "Whipped at the cart's tail", category: "Punishment" },
  { term: "Ambidexter", definition: "A lawyer who garners fees from both plaintiff and defender", category: "People" },
  { term: "Amuse", definition: "To fling dust into the eyes of someone to rob them; to deceive a shopkeeper", category: "Actions" },
  { term: "Amusers", definition: "A rogue who uses deception to rob", category: "People" },
  { term: "Anabaptist", definition: "A pickpocket caught and punished by being thrown into a pond", category: "Punishment" },
  { term: "Anglers", definition: "Petty thieves who steal goods with a hooked stick; those who draw in victims", category: "People" },
  { term: "Angling for coppers", definition: "Begging from a prison window with a cup on a string", category: "Actions" },
  { term: "Arch Rogue", definition: "The chief of a gang of thieves", category: "People" },
  { term: "Ard", definition: "Hot, stolen", category: "Descriptive" },
  { term: "Ark", definition: "A boat", category: "Objects" },
  { term: "Ark ruffians", definition: "River pirates who rob and murder passengers", category: "People" },
  { term: "Artichoke", definition: "Hang (see hearty choke)", category: "Execution" },
  { term: "Aunt", definition: "A prostitute or procurer", category: "People" },
  { term: "Autem Bawler", definition: "A priest", category: "People" },
  { term: "Autem Divers", definition: "Pickpockets who operate in churches", category: "People" },
  { term: "Autem Mort", definition: "A female beggar who hires children to inspire charity", category: "People" },
  { term: "Babes in the wood", definition: "Criminals in the stocks or pillory", category: "Punishment" },
  { term: "Badge", definition: "One who has had their hand burned as punishment for theft", category: "Punishment" },
  { term: "Bandog", definition: "A bailiff or sheriff", category: "People" },
  { term: "Barrow man", definition: "A man under sentence of transport", category: "People" },
  { term: "Bat", definition: "A common prostitute", category: "People" },
  { term: "Bawd", definition: "A prostitute", category: "People" },
  { term: "Bawdy basket", definition: "Criminal who sells items door to door but steals", category: "People" },
  { term: "Beak", definition: "A justice of the peace or magistrate", category: "People" },
  { term: "Beef", definition: "To cry beef is to give an alarm; to be in a man's beef is to wound him", category: "Actions" },
  { term: "Beggar maker", definition: "A tavern owner", category: "People" },
  { term: "Beilby's Ball", definition: "To dance with Beilby's ball is to be hanged", category: "Execution" },
  { term: "Bene", definition: "Good", category: "Descriptive" },
  { term: "Bene Bowse", definition: "Good beer", category: "Objects" },
  { term: "Bene Cove", definition: "Good fellow", category: "People" },
  { term: "Bene Darkmans", definition: "Good night", category: "Greetings" },
  { term: "Bene feaker", definition: "Counterfeiter", category: "People" },
  { term: "Ben", definition: "A fool", category: "People" },
  { term: "Bess", definition: "A crow bar", category: "Objects" },
  { term: "Betty", definition: "A crow bar", category: "Objects" },
  { term: "Bilboes", definition: "The stocks or prison", category: "Places" },
  { term: "Bilk", definition: "To cheat or con", category: "Actions" },
  { term: "Bing", definition: "To go or escape", category: "Actions" },
  { term: "Bingo", definition: "Brandy or other spirit", category: "Objects" },
  { term: "Bingo boy", definition: "A drinker of brandy", category: "People" },
  { term: "Bingo mort", definition: "A female drinker of brandy", category: "People" },
  { term: "Birds of a feather", definition: "Rogues of the same gang", category: "People" },
  { term: "Bite", definition: "To steal", category: "Actions" },
  { term: "Black art", definition: "The art of picking a lock", category: "Actions" },
  { term: "Black box", definition: "A lawyer", category: "People" },
  { term: "Blasted fellow", definition: "An abandoned rogue or prostitute", category: "People" },
  { term: "Blater", definition: "A stolen calf", category: "Objects" },
  { term: "Bleaters", definition: "Those cheated by a Jack in the Box", category: "People" },
  { term: "Bleating rig", definition: "Sheep stealing", category: "Actions" },
  { term: "Blow", definition: "To bite the blow is to steal the goods", category: "Actions" },
  { term: "Blue pigeons", definition: "Thieves who steal lead off buildings", category: "People" },
  { term: "Bluffer", definition: "An inn keeper", category: "People" },
  { term: "Blunt", definition: "Money", category: "Objects" },
  { term: "Boarding school", definition: "A prison", category: "Places" },
  { term: "Bob", definition: "Shoplifter's assistant; one who receives stolen goods", category: "People" },
  { term: "Boned", definition: "Seized, arrested", category: "Descriptive" },
  { term: "Boung", definition: "A purse", category: "Objects" },
  { term: "Boung nipper", definition: "A cut purse", category: "People" },
  { term: "Brimstone", definition: "An abandoned woman or thief", category: "People" },
  { term: "Bubber", definition: "A thief who steals from taverns", category: "People" },
  { term: "Bufe", definition: "A dog", category: "Objects" },
  { term: "Bufe nabber", definition: "A dog thief", category: "People" },
  { term: "Bug", definition: "To exchange a material for one of less value", category: "Actions" },
  { term: "Bung nipper", definition: "A pickpocket", category: "People" },
  { term: "Burning the ken", definition: "To flee a tavern without paying", category: "Actions" },
  { term: "Bus napper", definition: "A constable", category: "People" },
  { term: "Bus nappers kenchin", definition: "A watchman", category: "People" },
  { term: "Buttock and file", definition: "A prostitute who steals from clients", category: "People" },
  { term: "Button", definition: "A fake coin", category: "Objects" },
  { term: "Buzman", definition: "A pickpocket", category: "People" },
  { term: "Cackle", definition: "To inform on a thief", category: "Actions" },
  { term: "Calle", definition: "A cloak or gown worn as disguise", category: "Objects" },
  { term: "Canters", definition: "Thieves or beggars", category: "People" },
  { term: "Canting Crew", definition: "Thieves or beggars", category: "People" },
  { term: "Cap", definition: "Take an oath", category: "Actions" },
  { term: "Captain Sharp", definition: "A person who bullies those who refuse to pay gambling debts", category: "People" },
  { term: "Caravan", definition: "A large sum of money; one cheated of a large sum", category: "Objects" },
  { term: "Cattle", definition: "Prostitutes or gipsies", category: "People" },
  { term: "Charactered", definition: "To have your hand burnt as punishment for theft", category: "Punishment" },
  { term: "Charm", definition: "A lockpick", category: "Objects" },
  { term: "Chatts", definition: "The gallows", category: "Execution" },
  { term: "Clank", definition: "A silver tankard", category: "Objects" },
  { term: "Clank napper", definition: "A silver tankard stealer", category: "People" },
  { term: "Clear", definition: "Very drunk", category: "Descriptive" },
  { term: "Click", definition: "To hit", category: "Actions" },
  { term: "Clicker", definition: "The person who divides booty between thieves", category: "People" },
  { term: "Climb up a ladder to bed", definition: "To be hanged", category: "Execution" },
  { term: "Cloy", definition: "Steal", category: "Actions" },
  { term: "Cloyes", definition: "Thieves", category: "People" },
  { term: "Cly", definition: "A pocket", category: "Objects" },
  { term: "Cly the jerk", definition: "To be whipped", category: "Punishment" },
  { term: "Cockles, to cry", definition: "To be hanged", category: "Execution" },
  { term: "Colt", definition: "One who lends a horse to a highwayman; an apprentice thief", category: "People" },
  { term: "Confect", definition: "Counterfeited", category: "Descriptive" },
  { term: "Content", definition: "A person murdered for resisting a robbery", category: "People" },
  { term: "Cove", definition: "A man", category: "People" },
  { term: "Cracksman", definition: "A house breaker", category: "People" },
  { term: "Cramp word", definition: "The sentence of death", category: "Execution" },
  { term: "Crash", definition: "Kill", category: "Actions" },
  { term: "Crop", definition: "Hang", category: "Execution" },
  { term: "Cull", definition: "An honest man", category: "People" },
  { term: "Cullability", definition: "Easily cheated", category: "Descriptive" },
  { term: "Curbing law", definition: "The act of hooking items out of a window", category: "Actions" },
  { term: "Cursitor", definition: "A bad lawyer", category: "People" },
  { term: "Dangle", definition: "Hang", category: "Execution" },
  { term: "Darbies", definition: "Chains, handcuffs", category: "Objects" },
  { term: "Darby", definition: "Easy money", category: "Objects" },
  { term: "Darkee", definition: "A dark or hooded lantern", category: "Objects" },
  { term: "Darkmans", definition: "Night time", category: "Time" },
  { term: "Dawb", definition: "Bribe", category: "Actions" },
  { term: "Deadly nevergreen", definition: "Gallows", category: "Execution" },
  { term: "Derrick", definition: "A hangman", category: "People" },
  { term: "Dimber Damber", definition: "A chief thief", category: "People" },
  { term: "Ding Boy", definition: "A mugger", category: "People" },
  { term: "Dive", definition: "To pick a pocket; a thieves hideout", category: "Actions" },
  { term: "Dommerer", definition: "A beggar who pretends to be mute", category: "People" },
  { term: "Drag", definition: "To follow a cart or wagon to rob it", category: "Actions" },
  { term: "Draw-latches", definition: "Robbers of houses", category: "People" },
  { term: "Drawing the King's picture", definition: "Counterfeiting coins", category: "Actions" },
  { term: "Dromedary", definition: "A bungling thief", category: "People" },
  { term: "Dub", definition: "A lockpick", category: "Objects" },
  { term: "Dub Lay", definition: "To rob a house by picking its lock", category: "Actions" },
  { term: "Dummee", definition: "A pocket book or purse", category: "Objects" },
  { term: "Dumps", definition: "Coins made of lead", category: "Objects" },
  { term: "Die hard", definition: "Show no fear or remorse at the gallows", category: "Execution" },
  { term: "Earnest", definition: "A promise to pay", category: "Actions" },
  { term: "Equipt", definition: "Well dressed, rich", category: "Descriptive" },
  { term: "Fagger", definition: "A small boy passed through a window to open a door", category: "People" },
  { term: "Family man", definition: "A receiver of stolen goods", category: "People" },
  { term: "Fam lay", definition: "Palming an item to steal it", category: "Actions" },
  { term: "Fams", definition: "Gloves", category: "Objects" },
  { term: "Fen", definition: "A prostitute", category: "People" },
  { term: "Fence", definition: "To sell stolen goods; one who buys stolen goods", category: "People" },
  { term: "Fencing ken", definition: "A place where stolen goods are hidden", category: "Places" },
  { term: "Fidlam ben", definition: "Thieves", category: "People" },
  { term: "Figging law", definition: "The art of picking pockets", category: "Actions" },
  { term: "Figure dancer", definition: "One who alters numbers on notes of credit", category: "People" },
  { term: "Filcher", definition: "A petty thief who uses a hook", category: "People" },
  { term: "Flash ken", definition: "A thieves hideout", category: "Places" },
  { term: "Flash lingo", definition: "Thieves cant", category: "Language" },
  { term: "Floating hell", definition: "A prison ship", category: "Places" },
  { term: "Flog", definition: "To whip", category: "Punishment" },
  { term: "Fob", definition: "Cheat", category: "Actions" },
  { term: "Footpad", definition: "A common thief", category: "People" },
  { term: "Fork", definition: "To pick a pocket", category: "Actions" },
  { term: "Fortune teller", definition: "A judge", category: "People" },
  { term: "Foyst", definition: "A pickpocket", category: "People" },
  { term: "Frummagemmed", definition: "Strangled or hanged", category: "Execution" },
  { term: "Fun", definition: "A cheat or a trick", category: "Actions" },
  { term: "Fuzz", definition: "To pretend to shuffle a deck of cards", category: "Actions" },
  { term: "Gallows bird", definition: "A thief or pickpocket", category: "People" },
  { term: "Game", definition: "Any mode of robbery", category: "Actions" },
  { term: "Gamon", definition: "To deceive", category: "Actions" },
  { term: "Gaoler's coach", definition: "A cart used to take felons to execution", category: "Objects" },
  { term: "Gentleman's master", definition: "A highwayman", category: "People" },
  { term: "Gibberish", definition: "Thieves cant", category: "Language" },
  { term: "Gilt", definition: "A thief who picks locks", category: "People" },
  { term: "Ginny", definition: "A crowbar", category: "Objects" },
  { term: "Glazier", definition: "A thief who breaks windows to steal", category: "People" },
  { term: "Glim", definition: "A lantern used in housebreaking", category: "Objects" },
  { term: "Grease", definition: "Bribe", category: "Actions" },
  { term: "Gregorian tree", definition: "Gallows", category: "Execution" },
  { term: "Gudgeon", definition: "A gullible person", category: "People" },
  { term: "Gull", definition: "A gullible person; to cheat someone", category: "People" },
  { term: "Hamlet", definition: "A senior constable", category: "People" },
  { term: "Hang gallows look", definition: "A villainous appearance", category: "Descriptive" },
  { term: "Hang in chains", definition: "A vile, desperate person", category: "Descriptive" },
  { term: "Harman", definition: "A constable", category: "People" },
  { term: "Harmans", definition: "The stocks", category: "Punishment" },
  { term: "Hearty choke", definition: "To be hanged", category: "Execution" },
  { term: "Heave", definition: "To rob", category: "Actions" },
  { term: "Hempen fever", definition: "Death by hanging", category: "Execution" },
  { term: "Hempen widow", definition: "One whose husband was hanged", category: "People" },
  { term: "High pad", definition: "A highwayman", category: "People" },
  { term: "Hike", definition: "To run away", category: "Actions" },
  { term: "Hoist", definition: "To rob by entering through open windows", category: "Actions" },
  { term: "Hoodwink", definition: "Blindfold or fool someone", category: "Actions" },
  { term: "Hooked", definition: "Captured", category: "Descriptive" },
  { term: "Hookers", definition: "Petty thieves who use hooks", category: "People" },
  { term: "Hubbub", definition: "A riot", category: "Actions" },
  { term: "Hue", definition: "To whip", category: "Punishment" },
  { term: "Hush", definition: "Murder", category: "Actions" },
  { term: "Hush money", definition: "A bribe", category: "Objects" },
  { term: "Iron", definition: "Money", category: "Objects" },
  { term: "Ironmongers shop", definition: "To keep an ironmongers shop is to be hung in chains", category: "Execution" },
  { term: "Jack in a box", definition: "A card sharper", category: "People" },
  { term: "Jack Ketch", definition: "Hangman", category: "People" },
  { term: "Jail bird", definition: "Prisoner", category: "People" },
  { term: "Jammed", definition: "Hanged", category: "Execution" },
  { term: "Jem", definition: "A gold ring", category: "Objects" },
  { term: "Jemmy", definition: "A crow bar", category: "Objects" },
  { term: "Jigger", definition: "Whipping post", category: "Punishment" },
  { term: "Jordain", definition: "A stick or staff used by muggers", category: "Objects" },
  { term: "Juggler's box", definition: "The device used to burn criminals' hands", category: "Punishment" },
  { term: "Jukrum", definition: "Permission from the head of a thieves guild to operate", category: "Actions" },
  { term: "Kate", definition: "A lockpick", category: "Objects" },
  { term: "Ken", definition: "A house", category: "Places" },
  { term: "Ken Miller", definition: "Housebreaker", category: "People" },
  { term: "Ken Cracker", definition: "Housebreaker", category: "People" },
  { term: "Ketch", definition: "Hangman", category: "People" },
  { term: "Kiddeys", definition: "Young thieves", category: "People" },
  { term: "King's plate", definition: "Chains, shackles", category: "Objects" },
  { term: "King's pictures", definition: "Money", category: "Objects" },
  { term: "Knight of the blade", definition: "A bully", category: "People" },
  { term: "Knight of the post", definition: "A man willing to give fake evidence for money", category: "People" },
  { term: "Knight of the road", definition: "A highwayman", category: "People" },
  { term: "Laced mutton", definition: "A prostitute", category: "People" },
  { term: "Lag", definition: "A man transported for a crime", category: "People" },
  { term: "Land pirate", definition: "A highwayman", category: "People" },
  { term: "Lay", definition: "Danger", category: "Descriptive" },
  { term: "Leaf", definition: "To go with the fall of the leaf is to be hanged", category: "Execution" },
  { term: "Lift", definition: "Steal", category: "Actions" },
  { term: "Lightmans", definition: "Daytime", category: "Time" },
  { term: "Little snakesman", definition: "A small boy passed through a window to open a door", category: "People" },
  { term: "Long tongued", definition: "Unable to keep a secret", category: "Descriptive" },
  { term: "Lowre", definition: "Money", category: "Objects" },
  { term: "Lully priggers", definition: "Thieves who steal wet clothes off lines", category: "People" },
  { term: "Lurch", definition: "To be left in the lurch is to be betrayed", category: "Actions" },
  { term: "Mad Tom", definition: "A beggar who feigns madness", category: "People" },
  { term: "Made", definition: "Stolen", category: "Descriptive" },
  { term: "Made man", definition: "A member of the thieves guild", category: "People" },
  { term: "Maunding", definition: "Begging", category: "Actions" },
  { term: "Milch cow", definition: "One who is easily tricked out of money", category: "People" },
  { term: "Moabites", definition: "Bailiffs", category: "People" },
  { term: "Mobility", definition: "The commoners (pun on nobility)", category: "People" },
  { term: "Moon curser", definition: "A thief who uses darkness as cover", category: "People" },
  { term: "Moon men", definition: "Gipsies", category: "People" },
  { term: "Morning drop", definition: "The gallows", category: "Execution" },
  { term: "Mort", definition: "A woman", category: "People" },
  { term: "Moss", definition: "Lead stolen off buildings", category: "Objects" },
  { term: "Mot", definition: "A woman", category: "People" },
  { term: "Myrmidons", definition: "Constables", category: "People" },
  { term: "Nab", definition: "To seize", category: "Actions" },
  { term: "Nab the stoop", definition: "To be put in the stocks", category: "Punishment" },
  { term: "Napper", definition: "A cheat or thief", category: "People" },
  { term: "Napper of naps", definition: "A sheep stealer", category: "People" },
  { term: "Natty lads", definition: "Young thieves or pickpockets", category: "People" },
  { term: "Neck weed", definition: "Hemp to be made into rope", category: "Objects" },
  { term: "Needle point", definition: "A card sharper", category: "People" },
  { term: "New drop", definition: "The gallows", category: "Execution" },
  { term: "Newman's lift", definition: "The gallows", category: "Execution" },
  { term: "Nig", definition: "Metal clipped off a coin by a criminal", category: "Objects" },
  { term: "Night magistrate", definition: "A constable", category: "People" },
  { term: "Nim", definition: "To steal or pilfer", category: "Actions" },
  { term: "Nip", definition: "A cheat", category: "People" },
  { term: "Noisy dog racket", definition: "Stealing brass door knockers", category: "Actions" },
  { term: "Noozed", definition: "Hanged (or married)", category: "Execution" },
  { term: "Nose", definition: "An informer who betrays colleagues", category: "People" },
  { term: "Nubbing", definition: "Hanging", category: "Execution" },
  { term: "Nubbing cheat", definition: "The gallows", category: "Execution" },
  { term: "Nubbing cove", definition: "The hangman", category: "People" },
  { term: "Nubbing ken", definition: "The courthouse", category: "Places" },
  { term: "Nypper", definition: "A cutpurse", category: "People" },
  { term: "Oak", definition: "A rich man", category: "People" },
  { term: "Oaken towel", definition: "A cudgel", category: "Objects" },
  { term: "Office", definition: "To give office is to inform constables of a thief's activities", category: "Actions" },
  { term: "Old hand", definition: "An experienced thief", category: "People" },
  { term: "Onion", definition: "A seal or signet ring", category: "Objects" },
  { term: "Overseer", definition: "A man in the pillory or stocks", category: "Punishment" },
  { term: "Pad", definition: "The highway", category: "Places" },
  { term: "Pad borrowers", definition: "Horse thieves", category: "People" },
  { term: "Palaver", definition: "A tale told to avoid blame for a crime", category: "Actions" },
  { term: "Panny", definition: "House", category: "Places" },
  { term: "Parenthesis", definition: "The stocks", category: "Punishment" },
  { term: "Parings", definition: "Metal clipped off a coin by a criminal", category: "Objects" },
  { term: "Patter flash", definition: "To use thieves cant", category: "Language" },
  { term: "Paum", definition: "Conceal in the hand", category: "Actions" },
  { term: "Peach", definition: "Turn informer", category: "Actions" },
  { term: "Peeper", definition: "A spying glass (telescope)", category: "Objects" },
  { term: "Penance board", definition: "The pillory", category: "Punishment" },
  { term: "Petty fogger", definition: "A lawyer willing to take any case", category: "People" },
  { term: "Pig", definition: "An officer of the law", category: "People" },
  { term: "Pigeon", definition: "A person easy to cheat", category: "People" },
  { term: "Plate", definition: "Money, silver, gold", category: "Objects" },
  { term: "Plump in the pocket", definition: "Wealthy", category: "Descriptive" },
  { term: "Poney", definition: "Money", category: "Objects" },
  { term: "Pop", definition: "Pawn", category: "Actions" },
  { term: "Pop shop", definition: "Pawnbrokers", category: "Places" },
  { term: "Porridge", definition: "Prison", category: "Places" },
  { term: "Posse mobilitatis", definition: "A mob chasing a criminal", category: "People" },
  { term: "Poulterer", definition: "One who opens mail to steal money inside", category: "People" },
  { term: "Pound", definition: "Prison", category: "Places" },
  { term: "Prad lay", definition: "Cutting saddlebags to steal contents", category: "Actions" },
  { term: "Prad", definition: "A horse", category: "Objects" },
  { term: "Prig", definition: "A thief", category: "People" },
  { term: "Prig napper", definition: "A bounty hunter who catches thieves", category: "People" },
  { term: "Priggers", definition: "Thieves", category: "People" },
  { term: "Priggers of prancers", definition: "Horse thieves", category: "People" },
  { term: "Priggers of cacklers", definition: "Robbers of henhouses", category: "People" },
  { term: "Prince Prig", definition: "Head of a group of thieves", category: "People" },
  { term: "Provendor", definition: "The victim of a thief", category: "People" },
  { term: "Public ledger", definition: "A prostitute", category: "People" },
  { term: "Pull", definition: "Arrest", category: "Actions" },
  { term: "Puzzle-cause", definition: "A lawyer who doesn't understand the case", category: "People" },
  { term: "Quarromes", definition: "A body", category: "Objects" },
  { term: "Queer", definition: "To confuse someone", category: "Actions" },
  { term: "Queer bail", definition: "Someone who pretends to have money to act as surety", category: "People" },
  { term: "Queer birds", definition: "A person who returns to crime after release", category: "People" },
  { term: "Queer bit makers", definition: "Counterfeiters of coins", category: "People" },
  { term: "Queer bung", definition: "An empty purse", category: "Objects" },
  { term: "Queer cove", definition: "A thief", category: "People" },
  { term: "Queer cuffin", definition: "A justice of the peace", category: "People" },
  { term: "Queer ken", definition: "A prison", category: "Places" },
  { term: "Queer mort", definition: "A diseased prostitute", category: "People" },
  { term: "Quod", definition: "Prison", category: "Places" },
  { term: "Quota", definition: "A thief's share of booty", category: "Objects" },
  { term: "Rag", definition: "Paper money", category: "Objects" },
  { term: "Rank rider", definition: "A highwayman", category: "People" },
  { term: "Rap", definition: "Taking a false oath", category: "Actions" },
  { term: "Rascal", definition: "Rogue or villain", category: "People" },
  { term: "Rat", definition: "An informer; to turn informer", category: "People" },
  { term: "Rattling cove", definition: "A coachman", category: "People" },
  { term: "Rattling mumpers", definition: "Beggars who beg from coaches", category: "People" },
  { term: "Reader", definition: "A pocket book or purse", category: "Objects" },
  { term: "Reader merchants", definition: "Pickpockets", category: "People" },
  { term: "Ready", definition: "Money", category: "Objects" },
  { term: "Recruiting service", definition: "Highway robbery", category: "Actions" },
  { term: "Repository", definition: "A gaol", category: "Places" },
  { term: "Resurrection men", definition: "Those who steal bodies from churchyards", category: "People" },
  { term: "Rhino", definition: "Money", category: "Objects" },
  { term: "Ribbin", definition: "Money", category: "Objects" },
  { term: "Ringing the changes", definition: "Exchanging silver coins for less valuable metal", category: "Actions" },
  { term: "Roast", definition: "Arrest", category: "Actions" },
  { term: "Robert's men", definition: "Successful thieves", category: "People" },
  { term: "Rot gut", definition: "Cheap spiritous liquor", category: "Objects" },
  { term: "Rovers", definition: "Pirates, wandering thieves", category: "People" },
  { term: "Rub", definition: "Run away", category: "Actions" },
  { term: "Ruffles", definition: "Chains or shackles", category: "Objects" },
  { term: "Rufflers", definition: "Beggars who pretend to be wounded soldiers", category: "People" },
  { term: "Rug", definition: "Safe and secure", category: "Descriptive" },
  { term: "Rum", definition: "Fine, good, valuable", category: "Descriptive" },
  { term: "Rum beck", definition: "A justice of the peace", category: "People" },
  { term: "Rum bite", definition: "A clever trick", category: "Actions" },
  { term: "Rum bob", definition: "A skilled apprentice thief", category: "People" },
  { term: "Rum bung", definition: "A full purse", category: "Objects" },
  { term: "Rum cod", definition: "A purse filled with gold", category: "Objects" },
  { term: "Rum diver", definition: "A skilled pickpocket", category: "People" },
  { term: "Rum dubber", definition: "A skilled lock picker", category: "People" },
  { term: "Rum file", definition: "A skilled pickpocket", category: "People" },
  { term: "Rum fun", definition: "A clever trick", category: "Actions" },
  { term: "Rum pad", definition: "The highway", category: "Places" },
  { term: "Rum padders", definition: "Skilled and successful highwaymen", category: "People" },
  { term: "Rum prancer", definition: "A good horse", category: "Objects" },
  { term: "Rushers", definition: "Home invaders", category: "People" },
  { term: "Salmon", definition: "An oath taken by a beggar", category: "Actions" },
  { term: "Scapegallows", definition: "One who deserves and has escaped the gallows", category: "People" },
  { term: "Scragged", definition: "Hanged", category: "Execution" },
  { term: "Scragg'em fair", definition: "A public execution", category: "Execution" },
  { term: "Screw", definition: "A lock pick or skeleton key", category: "Objects" },
  { term: "Sham", definition: "A trick", category: "Actions" },
  { term: "Sharper", definition: "A con man", category: "People" },
  { term: "Sheriff's journeyman", definition: "Hangman", category: "People" },
  { term: "Sheriff's ball", definition: "An execution", category: "Execution" },
  { term: "Sheriff's hotel", definition: "Prison", category: "Places" },
  { term: "Sheriff's picture frame", definition: "Gallows", category: "Execution" },
  { term: "Shop", definition: "Prison", category: "Places" },
  { term: "Shoplifter", definition: "One who steals from a shop", category: "People" },
  { term: "Sing", definition: "Call out, inform", category: "Actions" },
  { term: "Slang", definition: "Chains or shackles; thieves cant", category: "Objects" },
  { term: "Slipgibbet", definition: "One who escaped the gallows", category: "People" },
  { term: "Snap the glaze", definition: "Break a window", category: "Actions" },
  { term: "Snapt", definition: "Captured", category: "Descriptive" },
  { term: "Sneak", definition: "A pilferer", category: "People" },
  { term: "Snoozing ken", definition: "Brothel", category: "Places" },
  { term: "Sop", definition: "A bribe", category: "Objects" },
  { term: "Spring-ankle warehouse", definition: "Prison", category: "Places" },
  { term: "Squeak", definition: "Escape; to confess", category: "Actions" },
  { term: "Squeakers", definition: "Organ pipes", category: "Objects" },
  { term: "Stalling ken", definition: "Place where stolen goods can be sold", category: "Places" },
  { term: "Star the glaze", definition: "Break a jeweller's window", category: "Actions" },
  { term: "Stoop", definition: "The pillory", category: "Punishment" },
  { term: "Stop hole abbey", definition: "The central hideout for a thieves guild", category: "Places" },
  { term: "Stretching", definition: "Hanging", category: "Execution" },
  { term: "Stuling ken", definition: "Place where stolen goods can be sold", category: "Places" },
  { term: "Swaddler", definition: "A thief who beats and murders victims", category: "People" },
  { term: "Swag", definition: "Booty", category: "Objects" },
  { term: "Sweating", definition: "Removing metal from a coin using chemicals", category: "Actions" },
  { term: "Swing", definition: "Hang", category: "Execution" },
  { term: "Tail", definition: "A prostitute", category: "People" },
  { term: "Tayle drawers", definition: "A thief who steals swords from belts", category: "People" },
  { term: "Teize", definition: "A flogging", category: "Punishment" },
  { term: "Thatch-gallows", definition: "A man of poor character", category: "People" },
  { term: "Thief takers", definition: "Someone who associates with thieves to arrest them", category: "People" },
  { term: "Three-legged mare", definition: "The gallows", category: "Execution" },
  { term: "Three legged stool", definition: "The gallows", category: "Execution" },
  { term: "Tom of Bedlam", definition: "A beggar who feigns madness", category: "People" },
  { term: "Topping cheat", definition: "The gallows", category: "Execution" },
  { term: "Topping cove", definition: "Hangman", category: "People" },
  { term: "Touch", definition: "Arrest", category: "Actions" },
  { term: "Trounce", definition: "Punish", category: "Punishment" },
  { term: "Tucked up", definition: "Hanged", category: "Execution" },
  { term: "Turncoat", definition: "One who has betrayed friends", category: "People" },
  { term: "Turn off", definition: "Hang", category: "Execution" },
  { term: "Twig", definition: "Realise that something is up", category: "Actions" },
  { term: "Two to one shop", definition: "Pawnbrokers", category: "Places" },
  { term: "Underdubber", definition: "A prison guard", category: "People" },
  { term: "Upright Man", definition: "Chief thief of a guild", category: "People" },
  { term: "Used up", definition: "Killed", category: "Descriptive" },
  { term: "Vamp", definition: "Pawn", category: "Actions" },
  { term: "Varlets", definition: "Criminals", category: "People" },
  { term: "Vincent's law", definition: "The art of cheating at cards", category: "Actions" },
  { term: "Vowel", definition: "To write an I.O.U.", category: "Actions" },
  { term: "Waterpad", definition: "River pirate", category: "People" },
  { term: "Wedge", definition: "Silver plate", category: "Objects" },
  { term: "Well-oaked", definition: "Wealthy", category: "Descriptive" },
  { term: "Whack", definition: "A share of booty obtained by fraud", category: "Objects" },
  { term: "Whip jacks", definition: "Thieves who pretend to be sailors", category: "People" },
  { term: "Wiper", definition: "Handkerchief", category: "Objects" },
  { term: "Wiper drawer", definition: "A pickpocket who steals handkerchiefs", category: "People" },
  { term: "Wooden ruff", definition: "Pillory", category: "Punishment" },
  { term: "Wry neck day", definition: "Day of execution", category: "Execution" },
  { term: "Yelp", definition: "Cry out for the police", category: "Actions" },
  { term: "Zad", definition: "A very crooked person", category: "People" },
];

export const englishToCant: Record<string, string[]> = {
  "abandoned person": ["blasted fellow", "brimstone", "lurch"],
  "arrested": ["boned", "hooked", "nabbed", "pulled", "roasted", "snapt", "touched"],
  "attack": ["mill"],
  "bad": ["queer", "foul"],
  "beer": ["bowse"],
  "buy": ["abloquir"],
  "catch": ["nab", "hook"],
  "city": ["burgh"],
  "come": ["aboule"],
  "friend": ["cull", "pal"],
  "get": ["nim", "prig"],
  "give": ["tip"],
  "go": ["pike", "toddle"],
  "gold": ["lowre", "ridge"],
  "guard": ["bandog", "harman"],
  "guarded": ["kanned", "watching"],
  "heavy": ["rum"],
  "him": ["cove"],
  "king": ["autem cackletub", "nob", "arch cove"],
  "knife": ["chive", "whittle"],
  "look": ["pike", "squint"],
  "lord": ["nob", "queer nob"],
  "meet": ["chouse"],
  "midday": ["lightmans noon"],
  "noon": ["lightmans high"],
  "noble": ["nob", "rum cove"],
  "queen": ["mort nob", "arch mort"],
  "quick": ["rum"],
  "quietly": ["prigging lay"],
  "rob": ["nim", "mill", "prig"],
  "run": ["pike", "scour"],
  "secret": ["privy"],
  "silver": ["wedge"],
  "speak": ["cant", "patter"],
  "sword": ["Toledo", "tuck"],
  "take": ["nim", "prig", "filch"],
  "target": ["mark", "cull"],
  "them": ["coves"],
  "tonight": ["darkmans"],
  "very": ["rum", "bene"],
  "wait": ["plant"],
  "walk": ["pad", "stalk"],
  "watch": ["ticker", "scout"],
  "wealth": ["lowre", "swag"],
  "wealthy": ["flush", "well-oaked", "plump in the pocket"],
  "beggars": ["abram men", "autem mort", "dommerer", "Mad Tom", "rattling mumpers", "rufflers", "Tom of Bedlam"],
  "begging": ["angling for coppers", "maunding"],
  "boat": ["ark"],
  "body": ["quarromes"],
  "booty": ["quota", "swag", "whack"],
  "brandy": ["bingo"],
  "bribe": ["dawb", "grease", "hush money", "sop"],
  "brothel": ["academy", "snoozing ken"],
  "calf, stolen": ["blater"],
  "call for police": ["cry beef"],
  "cart": ["gaoler's coach"],
  "cloak": ["calle"],
  "club": ["jordain", "oaken towel"],
  "coachman": ["rattling cove"],
  "coin, fake": ["button", "dump"],
  "con": ["amuse", "bilk", "fob", "fun", "fuzz", "hoodwink", "sham"],
  "con man": ["amuser", "jack in a box", "needle point", "nip", "sharper"],
  "counterfeiter": ["bene feaker", "figure dancer", "queer bit maker"],
  "counterfeited": ["confect"],
  "counterfeiting": ["drawing the King's picture", "sweating"],
  "courthouse": ["nubbing ken"],
  "criminals being transported": ["barrow man", "lag"],
  "criminals in the stocks": ["babes in the wood", "nappered", "overseer"],
  "crow bar": ["Bess", "Betty", "ginny", "jemmy"],
  "danger": ["lay"],
  "day": ["lightmans"],
  "death sentence": ["cramp word"],
  "dog": ["bufe"],
  "drunk": ["clear"],
  "escape": ["bing", "burning the ken", "hike", "rub"],
  "feign illness": ["sham abram"],
  "follow": ["drag"],
  "fool": ["Ben", "cullability", "gudgeon", "gull", "milch cow", "pigeon", "queer"],
  "gallows": ["chatts", "deadly nevergreen", "Gregorian Tree", "morning drop", "new drop", "Newman's lift", "nubbing cheat", "sheriff's picture frame", "three legged mare", "three legged stool", "topping cheat"],
  "gang": ["birds of a feather"],
  "gloves": ["fams"],
  "good": ["bene", "rum"],
  "hanged": ["acorn", "artichoked", "beilby's ball", "cry cockles", "cropped", "dangled", "frummagemmed", "hearty choked", "hempen fever", "ironmongers shop", "jammed", "leaf", "noozed", "nubbing", "scragged", "stretched", "swing", "turned off"],
  "hangman": ["Derrick", "Jack Ketch", "Ketch", "nubbing cove", "sheriff's journeyman", "topping cove"],
  "hideout": ["dive", "fencing ken", "flash ken", "stalling ken", "stop hole abbey", "stuling ken"],
  "highway": ["pad"],
  "highwayman": ["colt", "gentleman's master", "high pad", "knight of the road", "land pirate", "rank rider"],
  "hit": ["click"],
  "honest man": ["cull"],
  "house": ["ken", "panny"],
  "housebreaker": ["cracksman", "draw latch", "Ken Miller", "Ken Cracker", "rushers"],
  "inform": ["cackle", "long tongued", "nose", "office", "peach", "rat", "sing"],
  "judge": ["beak", "fortune teller", "queer cuffin"],
  "kill": ["crash", "use up"],
  "lantern": ["darkee", "glim"],
  "lawyer": ["black box", "cursitor", "petty fogger", "puzzle-case"],
  "lead": ["moss"],
  "license": ["jukrum"],
  "lie": ["amuse", "gamon", "palaver"],
  "lock pick": ["charm", "dub", "kate", "screw"],
  "lock picker": ["gilt"],
  "man": ["cove"],
  "money": ["blunt", "caravan", "iron", "King's pictures", "lowre", "plate", "poney", "rag", "ready", "rhino", "ribbin", "wedge"],
  "mugger": ["ding boy"],
  "murder": ["hush"],
  "naked": ["abram"],
  "night": ["darkmans"],
  "oath": ["cap", "earnest", "rap", "salmon"],
  "pawn": ["pop", "vamp"],
  "pawnbrokers": ["pop shop", "two to one shop"],
  "pickpocket": ["Adam Tiler", "anabaptist", "autem divers", "bung nipper", "buzman", "foyst", "natty lad", "nypper", "reader merchants"],
  "picking pockets": ["dive", "figging law", "forking"],
  "pocket": ["cly"],
  "police officer": ["bandog", "bus napper", "bus napper kenchin", "hamlet", "harman", "moabites", "myrmidons", "night magistrate", "pig"],
  "priest": ["autem bawler"],
  "prison": ["Bilboes", "boarding school", "porridge", "pound", "queer ken", "quod", "repository", "sheriff's hotel", "shop", "spring-ankle warehouse"],
  "prisoner": ["jail bird", "queer birds"],
  "prostitute": ["aunt", "bat", "bawd", "buttock and file", "cattle", "fen", "laced mutton", "public ledger", "queer mort", "tail"],
  "purse": ["boung", "dummee", "reader"],
  "receiver of stolen goods": ["family man", "fence"],
  "rich": ["equipt", "oak"],
  "ring": ["jem", "onion"],
  "riot": ["hubbub"],
  "secure": ["rug"],
  "shackles": ["darbies", "King's plate", "ruffles", "slang"],
  "sheep stealing": ["bleating rig"],
  "steal": ["bite", "bite the blow", "cloy", "curbing law", "heave", "hoist", "lift", "nim", "prad lay"],
  "stocks": ["Bilboes", "parenthesis", "penance board", "wooden ruff"],
  "stolen": ["ard", "made"],
  "tavern owner": ["beggar maker"],
  "theft": ["game"],
  "thief": ["Adam Tiler", "anglers", "ark ruffians", "autem divers", "bawdy basket", "blue pigeons", "Bob", "bubber", "bufe napper", "bung nipper", "buzman", "canters", "canting crew", "clank napper", "cloyes", "cracksman", "draw latches", "dromedary", "fagger", "fidlam ben", "filcher", "footpad", "foyst", "gallows bird", "gilt", "glazier", "hooker", "kiddeys", "little snakesman", "lully priggers", "made man", "moon curser", "napper of naps", "natty lads", "nypper", "old hand", "pad borrowers", "poulterer", "priggers", "priggers of prancers", "priggers of cacklers", "queer cove", "reader merchant", "resurrection men", "Robert's men", "rovers", "shoplifter", "sneak", "swaddler", "tayle drawer", "waterpad", "whip jack"],
  "thief, head": ["Arch Rogue", "Dimber Damber", "Prince Prig", "Upright Man"],
  "thieves cant": ["flash lingo", "gibberish", "patter flash", "slang"],
  "victim": ["content", "provendor"],
  "whipping": ["air and exercise", "cly the jerk", "flogging", "hue", "teize"],
  "whipping post": ["jigger"],
  "widow": ["ace of spades", "hempen widow"],
  "witness, fake": ["affidavit man", "knight of the post"],
  "woman": ["mort", "mot"],
  "wound": ["beef"],
};

// French translations for common terms (mapping French -> English -> Cant)
export const frenchToEnglish: Record<string, string> = {
  "voleur": "thief",
  "argent": "money",
  "prison": "prison",
  "potence": "gallows",
  "pendu": "hanged",
  "bourreau": "hangman",
  "voler": "steal",
  "mendiant": "beggars",
  "cachette": "hideout",
  "juge": "judge",
  "policier": "police officer",
  "prostituée": "prostitute",
  "taverne": "tavern owner",
  "nuit": "night",
  "jour": "day",
  "homme": "man",
  "femme": "woman",
  "bon": "good",
  "danger": "danger",
  "maison": "house",
  "route": "highway",
  "brigand": "highwayman",
  "évasion": "escape",
  "chaînes": "shackles",
  "bourse": "purse",
  "anneau": "ring",
  "lanterne": "lantern",
  "gants": "gloves",
  "ivresse": "drunk",
  "chien": "dog",
  "bateau": "boat",
  "corps": "body",
  "butin": "booty",
  "pot-de-vin": "bribe",
  "bordel": "brothel",
  "prêtre": "priest",
  "avocat": "lawyer",
  "tuer": "kill",
  "meurtre": "murder",
  "informer": "inform",
  "sûr": "secure",
  "riche": "rich",
  "fou": "fool",
  "émeute": "riot",
  "victime": "victim",
  "veuve": "widow",
  "nu": "naked",
  "serment": "oath",
  "frapper": "hit",
  "témoin": "witness, fake",
  "fouet": "whipping",
  "sentence de mort": "death sentence",
  "pièce fausse": "coin, fake",
  "faussaire": "counterfeiter",
  "chariot": "cart",
  "manteau": "cloak",
  "cocher": "coachman",
  "arnaque": "con",
  "escroc": "con man",
  "tribunal": "courthouse",
  "pied de biche": "crow bar",
  "pickpocket": "pickpocket",
  "poche": "pocket",
  "prisonnier": "prisoner",
  "receleur": "receiver of stolen goods",
  "volé": "stolen",
  "chef des voleurs": "thief, head",
  "jargon des voleurs": "thieves cant",
};

// Reverse mapping: English -> French (for Cant to French translation)
export const englishToFrench: Record<string, string> = {
  "thief": "voleur",
  "money": "argent",
  "prison": "prison",
  "gallows": "potence",
  "hanged": "pendu",
  "hangman": "bourreau",
  "steal": "voler",
  "beggars": "mendiant",
  "hideout": "cachette",
  "judge": "juge",
  "police officer": "policier",
  "prostitute": "prostituée",
  "tavern owner": "tavernier",
  "night": "nuit",
  "day": "jour",
  "man": "homme",
  "woman": "femme",
  "good": "bon",
  "danger": "danger",
  "house": "maison",
  "highway": "route",
  "highwayman": "brigand",
  "escape": "évasion",
  "shackles": "chaînes",
  "purse": "bourse",
  "ring": "anneau",
  "lantern": "lanterne",
  "gloves": "gants",
  "drunk": "ivresse",
  "dog": "chien",
  "boat": "bateau",
  "body": "corps",
  "booty": "butin",
  "bribe": "pot-de-vin",
  "brothel": "bordel",
  "priest": "prêtre",
  "lawyer": "avocat",
  "kill": "tuer",
  "murder": "meurtre",
  "inform": "informer",
  "secure": "sûr",
  "rich": "riche",
  "fool": "fou",
  "riot": "émeute",
  "victim": "victime",
  "widow": "veuve",
  "naked": "nu",
  "oath": "serment",
  "hit": "frapper",
  "witness, fake": "témoin",
  "whipping": "fouet",
  "death sentence": "sentence de mort",
  "coin, fake": "pièce fausse",
  "counterfeiter": "faussaire",
  "cart": "chariot",
  "cloak": "manteau",
  "coachman": "cocher",
  "con": "arnaque",
  "con man": "escroc",
  "courthouse": "tribunal",
  "crow bar": "pied de biche",
  "pickpocket": "pickpocket",
  "pocket": "poche",
  "prisoner": "prisonnier",
  "receiver of stolen goods": "receleur",
  "stolen": "volé",
  "thief, head": "chef des voleurs",
  "thieves cant": "jargon des voleurs",
  "lock pick": "crochet",
  "housebreaker": "cambrioleur",
  "stocks": "pilori",
  "cheat": "tricher",
  "deceive": "tromper",
  "rope": "corde",
  "sword": "épée",
  "knife": "couteau",
  "weapon": "arme",
  "gold": "or",
  "silver": "argent",
  "copper": "cuivre",
  "coin": "pièce",
  "watch": "montre",
  "jewelry": "bijoux",
  "goods": "marchandises",
  "food": "nourriture",
  "drink": "boisson",
  "beer": "bière",
  "brandy": "eau-de-vie",
  "wine": "vin",
};

// French Thieves Argot Dictionary - "Argot des Voleurs"
// Based on "Le nouveau dictionnaire complet du jargon de l'argot" by Arthur Halbert d'Angers (1849)
export interface ArgotEntry {
  term: string;
  definition: string;
  category?: string;
}

// Argot to French (Argot des voleurs -> Français)
export const argotToFrench: ArgotEntry[] = [
  { term: "Abbaye", definition: "Four (oven)", category: "Lieux" },
  { term: "Abbaye de monte-à-regret", definition: "L'échafaud (the scaffold/gallows)", category: "Exécution" },
  { term: "Abattoir", definition: "Cachot des condamnés (death row cell)", category: "Lieux" },
  { term: "Abloquir", definition: "Acheter (to buy)", category: "Actions" },
  { term: "Aboule", definition: "Viens (come here)", category: "Salutations" },
  { term: "Abouler", definition: "Venir (to come)", category: "Actions" },
  { term: "Acré/Acrie", definition: "Méfiance (distrust/suspicion)", category: "Descriptif" },
  { term: "Affe", definition: "La vie (life)", category: "Descriptif" },
  { term: "Affur", definition: "Profit (profit)", category: "Objets" },
  { term: "Affurer", definition: "Triompher, tromper (to triumph, to deceive)", category: "Actions" },
  { term: "Alpaga", definition: "Habit (clothing/coat)", category: "Objets" },
  { term: "Amadouage", definition: "Mariage (marriage)", category: "Actions" },
  { term: "Ambier", definition: "Fuir (to flee)", category: "Actions" },
  { term: "Angoulême", definition: "La bouche (the mouth)", category: "Corps" },
  { term: "Antiffe", definition: "Marche (walking/march)", category: "Actions" },
  { term: "Apôtres", definition: "Doigts (fingers)", category: "Corps" },
  { term: "Aquiger", definition: "Prendre (to take)", category: "Actions" },
  { term: "Arbif", definition: "En colère (angry)", category: "Descriptif" },
  { term: "Ardants", definition: "Les yeux (the eyes)", category: "Corps" },
  { term: "Argot", definition: "Bête (stupid/animal)", category: "Descriptif" },
  { term: "Arnaque", definition: "Agent de sûreté (police agent)", category: "Personnes" },
  { term: "Arpions", definition: "Les pieds (the feet)", category: "Corps" },
  { term: "Arquepincer", definition: "Prendre, saisir (to grab, seize)", category: "Actions" },
  { term: "Artie", definition: "Pain (bread)", category: "Objets" },
  { term: "Aspic", definition: "Avare (miser)", category: "Personnes" },
  { term: "Astic", definition: "Épée (sword)", category: "Objets" },
  { term: "Atiger", definition: "Blesser (to wound)", category: "Actions" },
  { term: "Atout", definition: "Du courage (courage)", category: "Descriptif" },
  { term: "Attache", definition: "Boucle (buckle)", category: "Objets" },
  { term: "Attrimer", definition: "Prendre (to take)", category: "Actions" },
  { term: "Au bonjour", definition: "Voler le matin pendant le sommeil (morning theft while victim sleeps)", category: "Actions" },
  { term: "Au clou", definition: "Être détenu (to be detained)", category: "Punition" },
  { term: "Au plan", definition: "En prison (in prison)", category: "Punition" },
  { term: "Babillard", definition: "Livre (book)", category: "Objets" },
  { term: "Babillarde", definition: "Lettre, épître (letter)", category: "Objets" },
  { term: "Babiller", definition: "Lire (to read)", category: "Actions" },
  { term: "Bachasse", definition: "Galère (galley ship/prison)", category: "Lieux" },
  { term: "Bacler", definition: "Fermer (to close/lock)", category: "Actions" },
  { term: "Baffrer", definition: "Manger (to eat)", category: "Actions" },
  { term: "Bagoul", definition: "Nom (name)", category: "Descriptif" },
  { term: "Baigneuse", definition: "Tête (head)", category: "Corps" },
  { term: "Baiser la camarde", definition: "Mourir (to die)", category: "Exécution" },
  { term: "Balle", definition: "Une livre ou un franc (a pound or franc)", category: "Objets" },
  { term: "Balluchon", definition: "Paquet (package/bundle)", category: "Objets" },
  { term: "Banquet", definition: "Banquier (banker)", category: "Personnes" },
  { term: "Barbaudier", definition: "Portier (doorman/porter)", category: "Personnes" },
  { term: "Barbillon", definition: "Qui reçoit de l'argent d'une prostituée (pimp)", category: "Personnes" },
  { term: "Barbotter", definition: "Fouiller (to search/rummage)", category: "Actions" },
  { term: "Basourdir", definition: "Abattre, frapper (to knock down, hit)", category: "Actions" },
  { term: "Bastringue", definition: "Scie pour scier le fer (hacksaw for iron)", category: "Objets" },
  { term: "Battage", definition: "Menée astucieuse (cunning scheme)", category: "Actions" },
  { term: "Batteur", definition: "Menteur (liar)", category: "Personnes" },
  { term: "Battre l'antiffe", definition: "Marcher (to walk)", category: "Actions" },
  { term: "Battre comptois", definition: "Faire le niais (to play dumb)", category: "Actions" },
  { term: "Bavarde", definition: "La bouche (the mouth)", category: "Corps" },
  { term: "Bécheur", definition: "Moqueur (mocker)", category: "Personnes" },
  { term: "Béguine", definition: "Aimer quelqu'un (to love someone)", category: "Actions" },
  { term: "Béquille", definition: "Potence (gallows)", category: "Exécution" },
  { term: "Béquilleur", definition: "Bourreau (executioner)", category: "Personnes" },
  { term: "Berlu", definition: "Aveugle (blind)", category: "Descriptif" },
  { term: "Bidoche", definition: "Viande (meat)", category: "Objets" },
  { term: "Bigorne", definition: "Langue de l'argot (thieves' cant)", category: "Langage" },
  { term: "Bigorneaux", definition: "Sergents de ville (police sergeants)", category: "Personnes" },
  { term: "Bille", definition: "Argent (money)", category: "Objets" },
  { term: "Binette", definition: "Figure (face)", category: "Corps" },
  { term: "Birbasse", definition: "Vieille femme (old woman)", category: "Personnes" },
  { term: "Blavin", definition: "Mouchoir (handkerchief)", category: "Objets" },
  { term: "Bloquer", definition: "Abandonner (to abandon)", category: "Actions" },
  { term: "Bogue en jonc", definition: "Montre d'or (gold watch)", category: "Objets" },
  { term: "Bogue en plâtre", definition: "Montre d'argent (silver watch)", category: "Objets" },
  { term: "Bonicard", definition: "Vieil homme (old man)", category: "Personnes" },
  { term: "Boniment", definition: "Mensonge (lie)", category: "Actions" },
  { term: "Boucher", definition: "Médecin (doctor)", category: "Personnes" },
  { term: "Bouclé", definition: "Enfermé (locked up)", category: "Punition" },
  { term: "Bouffarde", definition: "Pipe (smoking pipe)", category: "Objets" },
  { term: "Bouillante", definition: "Soupe (soup)", category: "Objets" },
  { term: "Bouis", definition: "Le fouet (the whip)", category: "Punition" },
  { term: "Boulanger", definition: "Le diable (the devil)", category: "Personnes" },
  { term: "Bouliner", definition: "Voler (to steal)", category: "Actions" },
  { term: "Boulotter", definition: "Manger (to eat)", category: "Actions" },
  { term: "Bourdon", definition: "Femme prostituée (prostitute)", category: "Personnes" },
  { term: "Boutange", definition: "Boutique (shop)", category: "Lieux" },
  { term: "Bras", definition: "Grand (big/tall)", category: "Descriptif" },
  { term: "Brèmes", definition: "Cartes à jouer (playing cards)", category: "Objets" },
  { term: "Bricard", definition: "Escalier (stairs)", category: "Lieux" },
  { term: "Bricule", definition: "Officier de paix (peace officer)", category: "Personnes" },
  { term: "Bride", definition: "Chaîne de montre (watch chain)", category: "Objets" },
  { term: "Brider", definition: "Fermer (to close/lock)", category: "Actions" },
  { term: "Brigante", definition: "Perruque (wig)", category: "Objets" },
  { term: "Broquante", definition: "Chose de peu de valeur (worthless thing)", category: "Objets" },
  { term: "Broque", definition: "Un liard (small coin)", category: "Objets" },
  { term: "Broquille", definition: "Bague (ring)", category: "Objets" },
  { term: "Brûlé", definition: "Déjoué (foiled/caught)", category: "Descriptif" },
  { term: "Brûler le pégriot", definition: "Faire disparaître la trace d'un vol (cover tracks after theft)", category: "Actions" },
  { term: "Bute", definition: "La guillotine (the guillotine)", category: "Exécution" },
  { term: "Buter", definition: "Tuer (to kill)", category: "Actions" },
  { term: "Caboche", definition: "Tête (head)", category: "Corps" },
  { term: "Cachemitte", definition: "Cachot (dungeon/cell)", category: "Lieux" },
  { term: "Cadet", definition: "Outil pour forcer les portes (door-forcing tool)", category: "Objets" },
  { term: "Cagou", definition: "Voleur solitaire (lone thief)", category: "Personnes" },
  { term: "Cambrioleur", definition: "Voleur de maisons (housebreaker)", category: "Personnes" },
  { term: "Cambriole", definition: "Chambre (room)", category: "Lieux" },
  { term: "Cambuse", definition: "Maison (house)", category: "Lieux" },
  { term: "Camelotte", definition: "Marchandise volée (stolen goods)", category: "Objets" },
  { term: "Camelotter", definition: "Vendre (to sell stolen goods)", category: "Actions" },
  { term: "Camoufle", definition: "Chandelle (candle)", category: "Objets" },
  { term: "Canard", definition: "Nouvelle mensongère (fake news)", category: "Actions" },
  { term: "Canne", definition: "Surveillance de la police (police surveillance)", category: "Descriptif" },
  { term: "Canton", definition: "Prison (prison)", category: "Lieux" },
  { term: "Cantonnier", definition: "Prisonnier (prisoner)", category: "Personnes" },
  { term: "Capir", definition: "Écrire (to write)", category: "Actions" },
  { term: "Carante", definition: "Table (table)", category: "Objets" },
  { term: "Carne", definition: "Charogne, mauvaise viande (rotten meat/scoundrel)", category: "Descriptif" },
  { term: "Carouble", definition: "Fausse clef (skeleton key)", category: "Objets" },
  { term: "Carrer (se)", definition: "Se cacher (to hide)", category: "Actions" },
  { term: "Caruche", definition: "Prison (prison)", category: "Lieux" },
  { term: "Casquer", definition: "Croire un mensonge (to believe a lie)", category: "Actions" },
  { term: "Cassantes", definition: "Noix (nuts)", category: "Objets" },
  { term: "Casser la hane", definition: "Couper la bourse (to cut a purse)", category: "Actions" },
  { term: "Casseroles", definition: "Mouchard (informer/snitch)", category: "Personnes" },
  { term: "Casseur de portes", definition: "Voleur avec effraction (burglar)", category: "Personnes" },
  { term: "Castu", definition: "Hôpital (hospital)", category: "Lieux" },
  { term: "Cavaler (se)", definition: "S'enfuir (to flee)", category: "Actions" },
  { term: "Cavée", definition: "Église (church)", category: "Lieux" },
  { term: "Chanté", definition: "Dénoncé (denounced/ratted out)", category: "Descriptif" },
  { term: "Chanteur", definition: "Voleur spéculant sur la bienfaisance (charity scam thief)", category: "Personnes" },
  { term: "Charlot", definition: "Le bourreau (the executioner)", category: "Personnes" },
  { term: "Chasse-noble", definition: "Gendarme (police officer)", category: "Personnes" },
  { term: "Chenu", definition: "Bon, beau (good, beautiful)", category: "Descriptif" },
  { term: "Chican", definition: "Marteau (hammer)", category: "Objets" },
  { term: "Chicard", definition: "Pas mal (not bad)", category: "Descriptif" },
  { term: "Chien", definition: "Secrétaire (secretary)", category: "Personnes" },
  { term: "Chiffon rouge", definition: "La langue (the tongue)", category: "Corps" },
  { term: "Chiffarde", definition: "Pipe (smoking pipe)", category: "Objets" },
  { term: "Chiquer", definition: "Battre (to beat)", category: "Actions" },
  { term: "Chopin", definition: "Objet volé (stolen object)", category: "Objets" },
  { term: "Choppé (être)", definition: "Être pris (to be caught)", category: "Punition" },
  { term: "Chouette", definition: "Beau, remarquable (beautiful, remarkable)", category: "Descriptif" },
  { term: "Chourineur", definition: "Tueur (killer)", category: "Personnes" },
  { term: "Claquer", definition: "Manger (to eat)", category: "Actions" },
  { term: "Clavigner", definition: "Vendanger (to harvest grapes/steal)", category: "Actions" },
  { term: "Clavin", definition: "Clou (nail)", category: "Objets" },
  { term: "Clavine", definition: "Vigne (vineyard)", category: "Lieux" },
  { term: "Coesre", definition: "Roi de l'argot (king of thieves)", category: "Personnes" },
  { term: "Coffier", definition: "Tuer (to kill)", category: "Actions" },
  { term: "Cogne", definition: "Gendarme (police officer)", category: "Personnes" },
  { term: "Colas", definition: "Le cou (the neck)", category: "Corps" },
  { term: "Combre", definition: "Un chapeau (a hat)", category: "Objets" },
  { term: "Combrie", definition: "Pièce d'un franc (one franc coin)", category: "Objets" },
  { term: "Commode", definition: "Cheminée (chimney/fireplace)", category: "Lieux" },
  { term: "Comte de caruche", definition: "Porte-clefs (jailer)", category: "Personnes" },
  { term: "Comte du canton", definition: "Un geôlier (a jailer)", category: "Personnes" },
  { term: "Côné", definition: "La mort (death)", category: "Exécution" },
  { term: "Connasse", definition: "Femme honnête (honest woman - ironic)", category: "Personnes" },
  { term: "Conombrer", definition: "Connaître (to know)", category: "Actions" },
  { term: "Coquer", definition: "Embrasser (to kiss/embrace)", category: "Actions" },
  { term: "Coquillard", definition: "Pèlerin (pilgrim - con artist)", category: "Personnes" },
  { term: "Coquin", definition: "Dénonciateur (informer/snitch)", category: "Personnes" },
  { term: "Coste", definition: "La mort (death)", category: "Exécution" },
  { term: "Cosne", definition: "Auberge (inn)", category: "Lieux" },
  { term: "Coulant", definition: "Lait (milk)", category: "Objets" },
  { term: "Courbe", definition: "Épaule (shoulder)", category: "Corps" },
  { term: "Coups de casseroles", definition: "Dénoncer ses camarades (to rat out accomplices)", category: "Actions" },
  { term: "Coups de fourchettes", definition: "Vol à l'aide de deux doigts (two-finger theft)", category: "Actions" },
  { term: "Couplard", definition: "Couteau (knife)", category: "Objets" },
  { term: "Craquelin", definition: "Menteur (liar)", category: "Personnes" },
  { term: "Cribler à la grive", definition: "Crier, avertir (to shout warning)", category: "Actions" },
  { term: "Crocs", definition: "Dents (teeth)", category: "Corps" },
  { term: "Crome", definition: "Crédit (credit)", category: "Objets" },
  { term: "Croisant", definition: "Gilet (vest)", category: "Objets" },
  { term: "Crucifié à ressort", definition: "Pistolets (pistols)", category: "Objets" },
  { term: "Cuisinier", definition: "Avocat (lawyer)", category: "Personnes" },
  { term: "Culbute", definition: "Culotte (trousers)", category: "Objets" },
  { term: "Curieux", definition: "Juge (judge)", category: "Personnes" },
  { term: "Dab", definition: "Père, maître (father, master)", category: "Personnes" },
  { term: "Dandillon", definition: "Cloche (bell)", category: "Objets" },
  { term: "Dardant", definition: "L'amour (love)", category: "Descriptif" },
  { term: "Daron", definition: "Maître, père (master, father)", category: "Personnes" },
  { term: "Daronne", definition: "Maîtresse, mère (mistress, mother)", category: "Personnes" },
  { term: "Daussière", definition: "Femme publique (prostitute)", category: "Personnes" },
  { term: "Débacler", definition: "Ouvrir (to open)", category: "Actions" },
  { term: "Débrider la lourde", definition: "Ouvrir la porte (to open the door)", category: "Actions" },
  { term: "Dèche", definition: "Perte, misère (loss, poverty)", category: "Descriptif" },
  { term: "Déchasse", definition: "Yeux (eyes)", category: "Corps" },
  { term: "Défargué", definition: "Déchargé (discharged/acquitted)", category: "Descriptif" },
  { term: "Défardeur", definition: "Voleur (thief)", category: "Personnes" },
  { term: "Déflouer la picouse", definition: "Voler le linge étendu (to steal hanging laundry)", category: "Actions" },
  { term: "Défourailler", definition: "Courir (to run)", category: "Actions" },
  { term: "Défrusquiné", definition: "Déshabillé (undressed)", category: "Descriptif" },
  { term: "Démurger", definition: "S'en aller (to leave)", category: "Actions" },
  { term: "Déplanquer", definition: "Déterrer (to dig up)", category: "Actions" },
  { term: "Dérondiner", definition: "Payer (to pay)", category: "Actions" },
  { term: "Désarrer", definition: "S'enfuir (to flee)", category: "Actions" },
  { term: "Dessous", definition: "Amant supplémentaire (secondary lover)", category: "Personnes" },
  { term: "Dessus", definition: "Amant en titre (main lover)", category: "Personnes" },
  { term: "Destuc", definition: "De moitié (half-and-half)", category: "Descriptif" },
  { term: "Détacher le bouchon", definition: "Couper la bourse (to cut a purse)", category: "Actions" },
  { term: "Détosse", definition: "Être ruiné (to be ruined)", category: "Descriptif" },
  { term: "Dette (payer une)", definition: "Être en prison (to be in prison)", category: "Punition" },
  { term: "Dévider le jars", definition: "Parler argot (to speak cant)", category: "Langage" },
  { term: "Diamants", definition: "Pavés (cobblestones)", category: "Objets" },
  { term: "Dominos", definition: "Dents (teeth)", category: "Corps" },
  { term: "Doublage", definition: "Larcin (theft)", category: "Actions" },
  { term: "Doublé", definition: "Volé (stolen)", category: "Descriptif" },
  { term: "Doubleur", definition: "Voleur (thief)", category: "Personnes" },
  { term: "Douilles", definition: "Cheveux (hair)", category: "Corps" },
  { term: "Dousse", definition: "Fièvre (fever)", category: "Descriptif" },
  { term: "Drague", definition: "Chirurgien (surgeon)", category: "Personnes" },
  { term: "Droguer", definition: "Demander (to ask/beg)", category: "Actions" },
  { term: "Durailles d'orphelins", definition: "Pierreries (jewels)", category: "Objets" },
  { term: "Dure", definition: "Pierre (stone)", category: "Objets" },
  { term: "Eau-daffe", definition: "Eau-de-vie (brandy)", category: "Objets" },
  { term: "Effaroucher", definition: "Voler (to steal)", category: "Actions" },
  { term: "Emballé", definition: "Être arrêté (to be arrested)", category: "Punition" },
  { term: "Embarras", definition: "Drap de lit (bed sheet)", category: "Objets" },
  { term: "Encensoir", definition: "Fressure (offal)", category: "Objets" },
  { term: "Endroguer", definition: "Chercher à faire fortune (to seek fortune)", category: "Actions" },
  { term: "Enflaquer", definition: "Se perdre (to get lost/ruined)", category: "Actions" },
  { term: "Enterner", definition: "Comprendre l'argot (to understand cant)", category: "Langage" },
  { term: "Entiffe", definition: "Église (church)", category: "Lieux" },
  { term: "Entonne", definition: "Chapelle (chapel)", category: "Lieux" },
  { term: "Entroller", definition: "Emporter (to carry away)", category: "Actions" },
  { term: "Épatter", definition: "Étonner (to astonish)", category: "Actions" },
  { term: "Épouser la faucanmère", definition: "Jeter ce qu'on a dérobé (to discard stolen goods when caught)", category: "Actions" },
  { term: "Épouser la veuve", definition: "Être pendu (to be hanged)", category: "Exécution" },
  { term: "Érailler l'ornie", definition: "Prendre la poule (to steal the chicken)", category: "Actions" },
  { term: "Esbrouffe", definition: "Prendre de force (to take by force)", category: "Actions" },
  { term: "Esbigner (s')", definition: "S'enfuir (to flee)", category: "Actions" },
  { term: "Escarpe", definition: "Assassin (murderer)", category: "Personnes" },
  { term: "Escaver", definition: "Empêcher (to prevent)", category: "Actions" },
  { term: "Escoute", definition: "Oreille (ear)", category: "Corps" },
  { term: "Espigner (s')", definition: "Se sauver (to escape)", category: "Actions" },
  { term: "Estuquer", definition: "Attraper un coup (to get hit)", category: "Actions" },
  { term: "Fagot", definition: "Forçat (convict)", category: "Personnes" },
  { term: "Faffes", definition: "Des papiers (papers/documents)", category: "Objets" },
  { term: "Fafio de sec", definition: "Vrai certificat (real certificate)", category: "Objets" },
  { term: "Fafio-lophe", definition: "Faux certificat (fake certificate)", category: "Objets" },
  { term: "Fanaudel", definition: "Camarade (comrade)", category: "Personnes" },
  { term: "Fauché (être)", definition: "Être mis à mort (to be executed)", category: "Exécution" },
  { term: "Faucheur", definition: "Bourreau (executioner)", category: "Personnes" },
  { term: "Fée", definition: "Amour, maîtresse (love, mistress)", category: "Personnes" },
  { term: "Ferlampier", definition: "Bandit (bandit)", category: "Personnes" },
  { term: "Fertille", definition: "Paille (straw)", category: "Objets" },
  { term: "Ficher la colle", definition: "Mentir adroitement (to lie skillfully)", category: "Actions" },
  { term: "Filer", definition: "Suivre un individu (to follow someone)", category: "Actions" },
  { term: "Filouser", definition: "Voler à la bourse (to pickpocket)", category: "Actions" },
  { term: "Fiole", definition: "Figure (face)", category: "Corps" },
  { term: "Flache", definition: "Plaisanterie (joke)", category: "Descriptif" },
  { term: "Flambarde", definition: "Chandelle (candle)", category: "Objets" },
  { term: "Flamber", definition: "Un poignard (a dagger)", category: "Objets" },
  { term: "Flanquer", definition: "Mettre (to put)", category: "Actions" },
  { term: "Floppée", definition: "Une volée (a beating)", category: "Punition" },
  { term: "Flouer", definition: "Jouer (to gamble)", category: "Actions" },
  { term: "Flouant", definition: "Jeu (gambling)", category: "Actions" },
  { term: "Fougue", definition: "Recéleur (fence for stolen goods)", category: "Personnes" },
  { term: "Fourgaine", definition: "Canne en jonc (reed cane)", category: "Objets" },
  { term: "Fourlineur", definition: "Homme qui vole dans les foules (crowd pickpocket)", category: "Personnes" },
  { term: "Frémillante", definition: "Assemblée (gathering)", category: "Lieux" },
  { term: "Frétillante", definition: "Danse (dance)", category: "Actions" },
  { term: "Frimouse", definition: "Physionomie (face/expression)", category: "Corps" },
  { term: "Frusques", definition: "Habillements (clothing)", category: "Objets" },
  { term: "Gaffre", definition: "Gardien de prison (prison guard)", category: "Personnes" },
  { term: "Galoche", definition: "Menton (chin)", category: "Corps" },
  { term: "Galier", definition: "Cheval (horse)", category: "Objets" },
  { term: "Galouser", definition: "Chanter (to sing)", category: "Actions" },
  { term: "Gance", definition: "Clique (gang)", category: "Personnes" },
  { term: "Gargoine", definition: "Le museau (the muzzle/face)", category: "Corps" },
  { term: "Gaux", definition: "Époux (husband)", category: "Personnes" },
  { term: "Gazouiller", definition: "Parler (to speak)", category: "Actions" },
  { term: "Gerber", definition: "Condamner (to sentence)", category: "Punition" },
  { term: "Gilbocque", definition: "Billard (billiards)", category: "Lieux" },
  { term: "Gironde", definition: "Fille perdue (fallen woman)", category: "Personnes" },
  { term: "Glace", definition: "Verre à boire (drinking glass)", category: "Objets" },
  { term: "Glacière-pendue", definition: "Réverbère (street lamp)", category: "Objets" },
  { term: "Gobilleur", definition: "Juge d'instruction (investigating judge)", category: "Personnes" },
  { term: "Gogueneau", definition: "Pot de nuit (chamber pot)", category: "Objets" },
  { term: "Gonzesse", definition: "Fille (girl)", category: "Personnes" },
  { term: "Goualer", definition: "Chanter (to sing)", category: "Actions" },
  { term: "Goupiner", definition: "Travailler (to work - at crime)", category: "Actions" },
  { term: "Gourde", definition: "Fausse pièce (counterfeit coin)", category: "Objets" },
  { term: "Grain", definition: "Écu (crown coin)", category: "Objets" },
  { term: "Gras", definition: "Argent (money)", category: "Objets" },
  { term: "Greffier", definition: "Chat (cat)", category: "Objets" },
  { term: "Grenier", definition: "Estomac (stomach)", category: "Corps" },
  { term: "Grinche", definition: "Voleur (thief)", category: "Personnes" },
  { term: "Grincher", definition: "Voler (to steal)", category: "Actions" },
  { term: "Grinchir", definition: "Voler (to steal)", category: "Actions" },
  { term: "Grive", definition: "Guerre (war)", category: "Descriptif" },
  { term: "Griveton", definition: "Soldat (soldier)", category: "Personnes" },
  { term: "Laffe", definition: "Peur (fear)", category: "Descriptif" },
  { term: "Lancequine", definition: "Pluie (rain)", category: "Descriptif" },
  { term: "Lansquiner", definition: "Pleuvoir (to rain)", category: "Actions" },
  { term: "Larbin", definition: "Domestique (servant)", category: "Personnes" },
  { term: "Lardé", definition: "Tué (killed)", category: "Exécution" },
  { term: "Larder", definition: "Tuer (to kill)", category: "Actions" },
  { term: "Largue", definition: "Femme (woman)", category: "Personnes" },
  { term: "Lazagne", definition: "Lettre (letter)", category: "Objets" },
  { term: "Lingre", definition: "Couteau (knife)", category: "Objets" },
  { term: "Litre", definition: "Habit (coat)", category: "Objets" },
  { term: "Loffée", definition: "Mauvaise affaire (bad deal)", category: "Descriptif" },
  { term: "Loupé", definition: "Manqué (missed/failed)", category: "Descriptif" },
  { term: "Lourde", definition: "Porte (door)", category: "Lieux" },
  { term: "Macchabée", definition: "Cadavre (corpse)", category: "Personnes" },
  { term: "Manche", definition: "Bras (arm)", category: "Corps" },
  { term: "Maquiller", definition: "Tricher (to cheat)", category: "Actions" },
  { term: "Marlou", definition: "Souteneur (pimp)", category: "Personnes" },
  { term: "Marner", definition: "Travailler dur (to work hard)", category: "Actions" },
  { term: "Matuche", definition: "Maison (house)", category: "Lieux" },
  { term: "Mec", definition: "Homme (man)", category: "Personnes" },
  { term: "Menteuse", definition: "Langue (tongue)", category: "Corps" },
  { term: "Mézigue", definition: "Moi (me)", category: "Personnes" },
  { term: "Mirettes", definition: "Yeux (eyes)", category: "Corps" },
  { term: "Môme", definition: "Enfant (child)", category: "Personnes" },
  { term: "Mornifle", definition: "Monnaie (change/coin)", category: "Objets" },
  { term: "Mouchard", definition: "Espion de police (police spy)", category: "Personnes" },
  { term: "Moucharder", definition: "Espionner (to spy)", category: "Actions" },
  { term: "Moulin", definition: "Estomac (stomach)", category: "Corps" },
  { term: "Naze", definition: "Syphilis (syphilis)", category: "Descriptif" },
  { term: "Nibergue", definition: "Rien (nothing)", category: "Descriptif" },
  { term: "Nippe", definition: "Vêtement (clothing)", category: "Objets" },
  { term: "Ogre", definition: "Niais (fool)", category: "Personnes" },
  { term: "Orphelin", definition: "Voleur d'argent (money thief)", category: "Personnes" },
  { term: "Pante", definition: "Bourgeois, victime (victim)", category: "Personnes" },
  { term: "Papelard", definition: "Papier (paper)", category: "Objets" },
  { term: "Paquet", definition: "Fortune (fortune)", category: "Objets" },
  { term: "Paumer", definition: "Perdre (to lose)", category: "Actions" },
  { term: "Pègre", definition: "Voleur (thief)", category: "Personnes" },
  { term: "Pégriot", definition: "Petit voleur (petty thief)", category: "Personnes" },
  { term: "Perpète", definition: "Perpétuité (life sentence)", category: "Punition" },
  { term: "Piaule", definition: "Chambre (room)", category: "Lieux" },
  { term: "Piausser", definition: "Coucher (to sleep)", category: "Actions" },
  { term: "Pied de biche", definition: "Pince-monseigneur (crowbar)", category: "Objets" },
  { term: "Pieu", definition: "Lit (bed)", category: "Objets" },
  { term: "Pioncer", definition: "Dormir (to sleep)", category: "Actions" },
  { term: "Placard", definition: "Affiche (poster)", category: "Objets" },
  { term: "Planquer", definition: "Cacher (to hide)", category: "Actions" },
  { term: "Pognon", definition: "Argent (money)", category: "Objets" },
  { term: "Poisse", definition: "Malchance (bad luck)", category: "Descriptif" },
  { term: "Poisser", definition: "Prendre, arrêter (to catch, arrest)", category: "Actions" },
  { term: "Poivrot", definition: "Ivrogne (drunkard)", category: "Personnes" },
  { term: "Ponte", definition: "Joueur (gambler)", category: "Personnes" },
  { term: "Poucif", definition: "Policier (policeman)", category: "Personnes" },
  { term: "Poulet", definition: "Policier (policeman)", category: "Personnes" },
  { term: "Prune", definition: "Amende (fine)", category: "Punition" },
  { term: "Quart", definition: "Commissariat (police station)", category: "Lieux" },
  { term: "Quart-d'œil", definition: "Commissaire (commissioner)", category: "Personnes" },
  { term: "Que dalle", definition: "Rien (nothing)", category: "Descriptif" },
  { term: "Radin", definition: "Avare (miser)", category: "Personnes" },
  { term: "Rade", definition: "Comptoir (counter)", category: "Lieux" },
  { term: "Rafiot", definition: "Bateau (boat)", category: "Objets" },
  { term: "Rapiat", definition: "Avare (miser)", category: "Personnes" },
  { term: "Raquer", definition: "Payer (to pay)", category: "Actions" },
  { term: "Ratiboisé", definition: "Ruiné (ruined)", category: "Descriptif" },
  { term: "Rebecquer", definition: "Se révolter (to revolt)", category: "Actions" },
  { term: "Refiler", definition: "Donner (to give)", category: "Actions" },
  { term: "Refroidi", definition: "Tué (killed)", category: "Exécution" },
  { term: "Refroidir", definition: "Tuer (to kill)", category: "Actions" },
  { term: "Renauder", definition: "Protester (to protest)", category: "Actions" },
  { term: "Rencardeur", definition: "Informateur (informer)", category: "Personnes" },
  { term: "Riffauder", definition: "Brûler (to burn)", category: "Actions" },
  { term: "Rigolade", definition: "Amusement (fun)", category: "Descriptif" },
  { term: "Riper", definition: "S'enfuir (to flee)", category: "Actions" },
  { term: "Roupiller", definition: "Dormir (to sleep)", category: "Actions" },
  { term: "Rupin", definition: "Riche (rich)", category: "Descriptif" },
  { term: "Sac", definition: "Dix francs (ten francs)", category: "Objets" },
  { term: "Saigner", definition: "Tuer (to kill)", category: "Actions" },
  { term: "Sans-dent", definition: "Vieux (old person)", category: "Personnes" },
  { term: "Sape", definition: "Vêtements (clothes)", category: "Objets" },
  { term: "Saucée", definition: "Pluie (rain)", category: "Descriptif" },
  { term: "Schpile", definition: "Jeu de cartes (card game)", category: "Actions" },
  { term: "Schnock", definition: "Imbécile (fool)", category: "Personnes" },
  { term: "Sécher", definition: "Attendre (to wait)", category: "Actions" },
  { term: "Seriner", definition: "Répéter (to repeat)", category: "Actions" },
  { term: "Serpillière", definition: "Robe (dress)", category: "Objets" },
  { term: "Serré (être)", definition: "Être arrêté (to be arrested)", category: "Punition" },
  { term: "Singe", definition: "Patron (boss)", category: "Personnes" },
  { term: "Soiffard", definition: "Ivrogne (drunkard)", category: "Personnes" },
  { term: "Sorgue", definition: "Nuit (night)", category: "Temps" },
  { term: "Surin", definition: "Couteau (knife)", category: "Objets" },
  { term: "Suriner", definition: "Poignarder (to stab)", category: "Actions" },
  { term: "Tabar", definition: "Tabac (tobacco)", category: "Objets" },
  { term: "Tacot", definition: "Voiture (car/vehicle)", category: "Objets" },
  { term: "Taffe", definition: "Peur (fear)", category: "Descriptif" },
  { term: "Tapin", definition: "Tambour (drum)", category: "Objets" },
  { term: "Tapis", definition: "Tripot (gambling den)", category: "Lieux" },
  { term: "Taule", definition: "Prison (prison)", category: "Lieux" },
  { term: "Taulier", definition: "Hôtelier (innkeeper)", category: "Personnes" },
  { term: "Tête de lard", definition: "Imbécile (fool)", category: "Personnes" },
  { term: "Tiffes", definition: "Cheveux (hair)", category: "Corps" },
  { term: "Tire-jus", definition: "Mouchoir (handkerchief)", category: "Objets" },
  { term: "Tireur", definition: "Pickpocket (pickpocket)", category: "Personnes" },
  { term: "Toc", definition: "Faux (fake)", category: "Descriptif" },
  { term: "Tombé", definition: "Arrêté (arrested)", category: "Punition" },
  { term: "Tomber", definition: "Arrêter (to arrest)", category: "Actions" },
  { term: "Tonton", definition: "Receleur (fence)", category: "Personnes" },
  { term: "Torcher", definition: "Battre (to beat)", category: "Actions" },
  { term: "Toquante", definition: "Montre (watch)", category: "Objets" },
  { term: "Tourmente", definition: "Guillotine (guillotine)", category: "Exécution" },
  { term: "Tournante", definition: "Clé (key)", category: "Objets" },
  { term: "Trèfle", definition: "Tabac (tobacco)", category: "Objets" },
  { term: "Trimard", definition: "Route (road)", category: "Lieux" },
  { term: "Trimarder", definition: "Vagabonder (to wander)", category: "Actions" },
  { term: "Trombine", definition: "Figure (face)", category: "Corps" },
  { term: "Trouillard", definition: "Peureux (coward)", category: "Personnes" },
  { term: "Truand", definition: "Mendiant, voleur (beggar, thief)", category: "Personnes" },
  { term: "Truander", definition: "Mendier, voler (to beg, steal)", category: "Actions" },
  { term: "Turbin", definition: "Travail (work)", category: "Actions" },
  { term: "Turbiner", definition: "Travailler (to work)", category: "Actions" },
  { term: "Valdingue", definition: "Valise (suitcase)", category: "Objets" },
  { term: "Vanne", definition: "Moquerie (mockery)", category: "Actions" },
  { term: "Veille", definition: "Femme âgée (old woman)", category: "Personnes" },
  { term: "Zigoteau", definition: "Homme (man/guy)", category: "Personnes" },
];

// French to Argot (Français -> Argot des voleurs)
export const frenchToArgot: Record<string, string> = {
  "argent": "bille, gras, pognon",
  "assassin": "escarpe",
  "avocat": "cuisinier",
  "bateau": "rafiot",
  "bourreau": "béquilleur, faucheur, charlot",
  "cadavre": "macchabée",
  "chambre": "cambriole, piaule",
  "chandelle": "camoufle, flambarde",
  "chapeau": "combre",
  "cheval": "galier",
  "cheveux": "douilles, tiffes",
  "clé": "tournante",
  "couteau": "couplard, lingre, surin",
  "dents": "crocs, dominos",
  "église": "cavée, entiffe",
  "enfant": "môme",
  "exécuté": "fauché",
  "femme": "largue, gonzesse",
  "figure": "binette, fiole, frimouse, trombine",
  "forçat": "fagot",
  "fuir": "ambier, se cavaler, s'esbigner, désarrer",
  "gendarme": "cogne, chasse-noble",
  "guillotine": "bute, tourmente",
  "homme": "mec, zigoteau",
  "hôpital": "castu",
  "informateur": "casseroles, coquin, mouchard",
  "juge": "curieux, gobilleur",
  "lettre": "babillarde, lazagne",
  "lit": "pieu",
  "livre": "babillard",
  "maison": "cambuse, matuche",
  "manger": "baffrer, béquiller, boulotter, claquer",
  "montre": "bogue, toquante",
  "mort": "côné, coste",
  "mourir": "baiser la camarde",
  "nuit": "sorgue",
  "ouvrir": "débacler, débrider",
  "pain": "artie",
  "papiers": "faffes",
  "père": "dab, daron",
  "pickpocket": "fourlineur, tireur",
  "pipe": "bouffarde, chiffarde",
  "policier": "arnaque, bigorneaux, poulet, poucif",
  "porte": "lourde",
  "potence": "béquille",
  "prendre": "aquiger, arquepincer, attrimer",
  "prison": "canton, caruche, taule",
  "prisonnier": "cantonnier",
  "prostituée": "bourdon, daussière",
  "recéleur": "fougue, tonton",
  "tête": "baigneuse, caboche",
  "tuer": "buter, coffier, larder, refroidir, saigner, suriner",
  "victime": "pante",
  "vieux": "bonicard, sans-dent",
  "voler": "bouliner, effaroucher, grincher",
  "voleur": "cagou, défardeur, doubleur, grinche, pègre, truand",
  "yeux": "ardants, déchasse, mirettes",
};

// French categories
export const frenchCategories = [
  "Personnes",
  "Actions",
  "Objets",
  "Lieux",
  "Exécution",
  "Punition",
  "Descriptif",
  "Temps",
  "Langage",
  "Corps",
  "Salutations"
];

// Hobo symbols data
export interface HoboSymbol {
  name: string;
  meaning: string;
  symbol: string; // Unicode or description
  category: string;
}

export const hoboSymbols: HoboSymbol[] = [
  { name: "Circle with Two Arrows", meaning: "Get out fast - danger", symbol: "⊛", category: "Warning" },
  { name: "Top Hat & Triangle", meaning: "Rich man lives here", symbol: "▲", category: "Resource" },
  { name: "Cross", meaning: "Religious talk will get you food", symbol: "✚", category: "Resource" },
  { name: "Cat", meaning: "Kind woman lives here", symbol: "🐱", category: "Resource" },
  { name: "Circle with Arrows Pointing In", meaning: "Defend yourself - hostile homeowner", symbol: "⊕", category: "Warning" },
  { name: "Horizontal Zigzag", meaning: "Barking dog", symbol: "〰", category: "Warning" },
  { name: "Triangle with Hands", meaning: "Man with gun lives here", symbol: "△!", category: "Warning" },
  { name: "Two Interlocking Circles", meaning: "Handcuffs - police nearby", symbol: "∞", category: "Warning" },
  { name: "Cross with Circle", meaning: "Angel food - food given freely", symbol: "⊕", category: "Resource" },
  { name: "Curved Line Pointing Right", meaning: "Go this way", symbol: "→", category: "Direction" },
  { name: "Square with Diagonal", meaning: "Safe camp", symbol: "⬜", category: "Resource" },
  { name: "Three Diagonal Lines", meaning: "Unsafe place", symbol: "///", category: "Warning" },
  { name: "Comb Shape", meaning: "Free doctors here", symbol: "⫿", category: "Resource" },
  { name: "Rectangle", meaning: "Good road to travel", symbol: "▭", category: "Direction" },
  { name: "Circle with Dot", meaning: "Nothing to gain here", symbol: "◉", category: "Warning" },
  { name: "Two Shovels", meaning: "Work available", symbol: "⚒", category: "Resource" },
  { name: "Knife and Fork", meaning: "Food for work", symbol: "🍴", category: "Resource" },
  { name: "Wavy Lines", meaning: "Water available", symbol: "≈", category: "Resource" },
  { name: "Bird Shape", meaning: "Leave quickly", symbol: "✧", category: "Warning" },
  { name: "Clock Shape", meaning: "Best time to call", symbol: "⏰", category: "Info" },
  { name: "Campfire", meaning: "Camped here before", symbol: "🔥", category: "Info" },
  { name: "Dollar Sign", meaning: "Money to be had", symbol: "$", category: "Resource" },
  { name: "House Shape", meaning: "Safe shelter", symbol: "⌂", category: "Resource" },
  { name: "Tree", meaning: "Good place to sleep outdoors", symbol: "🌲", category: "Resource" },
  { name: "X Mark", meaning: "Don't go this way", symbol: "✗", category: "Warning" },
  { name: "Arrow with Line", meaning: "Hop a train here", symbol: "⟼", category: "Direction" },
  { name: "Horizontal Line", meaning: "Doubtful", symbol: "—", category: "Info" },
  { name: "Spiral", meaning: "Police station", symbol: "🌀", category: "Warning" },
  { name: "Stars", meaning: "Sleep in this barn", symbol: "★", category: "Resource" },
  { name: "Teeth Shape", meaning: "Mean dog", symbol: "⋏", category: "Warning" },
  { name: "Four Straight Lines", meaning: "Housewife will feed for work", symbol: "||||", category: "Resource" },
  { name: "Open Mug", meaning: "This town serves alcohol", symbol: "∪", category: "Info" },
  { name: "House with Slash", meaning: "Heavily guarded home", symbol: "⌂/", category: "Warning" },
  { name: "Two Overlapping Squares", meaning: "Can get anything by threatening", symbol: "⧉", category: "Warning" },
  { name: "Double Diamond", meaning: "Keep quiet or baby is here", symbol: "⚭", category: "Info" },
];

// D&D Thieves Guild Symbols
export const thievesGuildSymbols = [
  { name: "Dagger Mark", meaning: "Member of the guild", symbol: "🗡️", category: "Identity" },
  { name: "Coin with Slash", meaning: "Payment expected", symbol: "⊘", category: "Commerce" },
  { name: "Open Eye", meaning: "This place is watched", symbol: "👁️", category: "Warning" },
  { name: "Closed Eye", meaning: "Safe from prying eyes", symbol: "◡", category: "Safe" },
  { name: "Crossed Keys", meaning: "Fence operates here", symbol: "⚿", category: "Commerce" },
  { name: "Broken Chain", meaning: "Safe house for escaped prisoners", symbol: "⛓️‍💥", category: "Safe" },
  { name: "Hooded Figure", meaning: "Assassin contact", symbol: "👤", category: "Contact" },
  { name: "Crescent Moon", meaning: "Best time to operate: night", symbol: "☽", category: "Info" },
  { name: "Sun with Line", meaning: "Guard patrol schedule", symbol: "☀️", category: "Info" },
  { name: "Skull Mark", meaning: "Death awaits trespassers", symbol: "☠️", category: "Warning" },
  { name: "Rat", meaning: "Informant in area", symbol: "🐀", category: "Warning" },
  { name: "Spider Web", meaning: "Guild territory", symbol: "🕸️", category: "Territory" },
  { name: "Lock Symbol", meaning: "Skilled locks - extra caution", symbol: "🔒", category: "Info" },
  { name: "Pouch Shape", meaning: "Easy marks frequent here", symbol: "👝", category: "Resource" },
  { name: "Crown", meaning: "Noble target", symbol: "👑", category: "Target" },
  { name: "Hammer", meaning: "Blacksmith can modify equipment", symbol: "🔨", category: "Resource" },
  { name: "Ale Mug", meaning: "Tavern with guild connections", symbol: "🍺", category: "Safe" },
  { name: "Feather", meaning: "Scribe for forged documents", symbol: "🪶", category: "Resource" },
  { name: "Ship", meaning: "Smuggling route", symbol: "⛵", category: "Route" },
  { name: "Horse", meaning: "Quick escape available", symbol: "🐴", category: "Escape" },
  { name: "Crossed Swords", meaning: "Danger or monsters ahead", symbol: "⚔️", category: "Warning" },
  { name: "Gold Coin", meaning: "Loot or treasure inside", symbol: "🪙", category: "Resource" },
  { name: "Footprints", meaning: "Keep moving / don't stop", symbol: "👣", category: "Direction" },
  { name: "Hand Sign", meaning: "Wait here or halt", symbol: "✋", category: "Direction" },
  { name: "Open Door", meaning: "Open or unsecured", symbol: "🚪", category: "Info" },
  { name: "Sparkles", meaning: "Magic presence or spellcaster", symbol: "✨", category: "Info" },
];

export const categories = [
  "People",
  "Actions",
  "Objects",
  "Places",
  "Execution",
  "Punishment",
  "Descriptive",
  "Time",
  "Language",
  "Greetings"
];
